import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
	title: "AAAAAAAAAAAAbout",
	description: "Generated by create next app",
};

type AboutPageProps = {
	children: React.ReactNode;
};

export default function AboutPage({ children }: Readonly<AboutPageProps>) {
	console.log("Lado de lá");

	return (
		<>
			{children}
			Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut rerum,
			quidem consequuntur aperiam excepturi qui, facere voluptatum
			voluptatibus ipsa enim corrupti sit reiciendis animi provident
			expedita eius pariatur debitis. Suscipit.
		</>
	);
}
