import { Heading } from '@/components/Heading';
import { findAllPublicPostsCached } from '@/libs/post/queries';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
	title: 'About',
	description: 'Generated by create next app',
};

export default async function AboutPage() {
	const posts = await findAllPublicPostsCached();
	const post = posts[2];
	return (
		<>
			<Heading url={post.slug} as='h1'>
				{post.title}
			</Heading>
		</>
	);
}
