import { PostsList } from '@/components/PostsList';
import { SpinLoader } from '@/components/SpinLoader';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
	title: 'Blog',
	description: 'Generated by create next app',
};

export default async function Home() {
	return (
		<>
			<Suspense fallback={<SpinLoader />}>
				<PostsList />
				<p className='text-justify py-8'>
					Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore totam
					dicta consequuntur pariatur nihil, autem et. Similique mollitia,
					laboriosam, quidem inventore id voluptas sapiente dolore ad odio,
					debitis iure provident? Vero illum earum nisi soluta voluptatem ad
					eaque minus tempora illo, ut quas ipsam nobis laudantium distinctio.
					Temporibus quod aliquam rem repellat quasi, veniam vero cum ipsum
					ullam! Illum, quisquam. Voluptatibus dolore amet unde omnis vitae.
					Nisi, atque voluptate. Maxime et nemo, eveniet, corporis alias
					architecto unde delectus esse adipisci voluptas numquam itaque dolor
					corrupti optio doloribus natus perferendis necessitatibus? Numquam at
					ratione itaque. Amet quis aliquam, illum voluptatibus omnis beatae
					sapiente modi aspernatur delectus suscipit voluptas. Rerum temporibus
					quaerat vitae laboriosam soluta praesentium repellat? Aspernatur in
					eveniet officiis rerum? Est tempora nulla, perspiciatis deleniti culpa
					vero corporis, laudantium quisquam optio impedit at adipisci itaque
					sunt quasi sequi quod fugit earum enim illum, libero necessitatibus
					dolorem exercitationem! Quae, sequi quam. Repudiandae minima, aperiam
					quasi, sequi deserunt laboriosam dolor expedita aliquam quidem
					provident odit dicta doloremque suscipit atque! Culpa quam voluptas
					commodi sit laboriosam expedita, ad inventore, ratione quo, nam ipsam.
					Dolor eaque magni rem, temporibus non, odio repellendus iure modi
					deleniti cumque incidunt explicabo aliquid laborum odit numquam fugiat
					asperiores, maiores quibusdam dolore est maxime atque nihil! Illum,
					ullam architecto? Dolor earum saepe quam et eius deserunt voluptates
					laborum minus vitae ipsam sit possimus reprehenderit perspiciatis,
					sint eos veritatis incidunt recusandae. Alias iusto velit maiores
					deleniti facilis architecto, repudiandae magni. Asperiores ad ducimus
					consequatur, quasi voluptatum mollitia consectetur necessitatibus
					fugiat tempora, velit molestiae quia minus id nihil perspiciatis nemo
					recusandae possimus alias at. Doloribus illum esse quas, nulla veniam
					quibusdam? Cupiditate aspernatur eligendi perspiciatis, voluptates
					mollitia, esse explicabo molestiae officiis asperiores repellat sunt
					minima nobis odio aliquam quaerat placeat adipisci pariatur sed atque
					laudantium inventore facilis. Eaque repudiandae quasi laborum!
					Dignissimos, ea. Deserunt consectetur dicta debitis. Quibusdam porro
					facere eius alias quas tempora odit, at, quis dicta hic adipisci ullam
					autem ad, quia doloremque eum qui repellendus. Quos, beatae ipsa. Ex
					adipisci quos a aut dignissimos sunt. Cupiditate consectetur
					necessitatibus quod veniam, reiciendis quas? Accusantium inventore
					natus quia iste. Voluptatibus, dolores? Placeat voluptatum repellendus
					illo mole
				</p>
			</Suspense>
		</>
	);
}
