import { PostsList } from '@/components/PostsList';
import { SpinLoader } from '@/components/SpinLoader';
import { Suspense } from 'react';
import { PostFeatured } from '@/components/PostFeatured';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'The Blog',
	description: 'Generated by create next app',
};

export default async function Home() {
	return (
		<>
			<Suspense fallback={<SpinLoader className='min-h-20 mb-10' />}>
				<PostFeatured />
				<PostsList />
			</Suspense>
		</>
	);
}
